@startuml succes_process_model

skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Process Manage Products" {

  ' Proceso principal
  class "ManageProductsProcessing" <<process>> {
  }

  ' Subprocesos CRUD
  class "ProductListing" <<process>> {
  }
  class "ProductCreation" <<process>> {
  }
  class "ProductUpdate" <<process>> {
  }
  class "ProductDeletion" <<process>> {
  }

  ' Entrada de datos (crear/editar)
  class "ProductDataInput" <<process>> {
    -etiqueta : String
    -fotoUrl : String
    -nombre : String
    -descripcion : String
    -cantidadExistencia : Int
    --
    -validateData()
  }

  ' Confirmaciones
  class "CreateConfirmation" <<process>> {
    -productCreated()
  }
  class "UpdateConfirmation" <<process>> {
    -productUpdated()
  }
  class "DeleteConfirmation" <<process>> {
    -productDeleted()
  }

  ' Error
  class "ValidationError" <<process>> {
    -message : String
  }

  ' Estructura 
  ManageProductsProcessing *-- ProductListing
  ManageProductsProcessing *-- ProductCreation
  ManageProductsProcessing *-- ProductUpdate
  ManageProductsProcessing *-- ProductDeletion

  ' Entradas y resultados por subproceso
  ProductCreation *-- ProductDataInput
  ProductCreation *-- CreateConfirmation
  ProductDataInput --> ValidationError

  ProductUpdate *-- ProductDataInput
  ProductUpdate *-- UpdateConfirmation

  ProductDeletion *-- DeleteConfirmation
}




@enduml
