@startuml customer_user_interest_save_process_flow
skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam activity {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

title Proceso Guardar Interes

start

:Boton Guardar Interés pulsado;

:<<userAction>>\nDatos Entrada Interés;

if (Confirmar Guardado?) then (cancelar)
  :Cancelar;
else (ok)
  :<<systemAction>>\nGuardar Interés;
  :<<systemAction>>\nActualizar Vista; 
endif
stop
@enduml


