@startuml adminPage_requirements
allow_mixing

skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Requirements Admin Page" {
  actor "Usuario Administrador" as Admin

  usecase "Login" as Login <<processing>>
  usecase "Crear Tienda Colectiva" as CreateShop <<processing>>
  usecase "Ver Detalle Tienda" as ViewShopDetail <<browsing>>
  usecase "Habilidar/Deshabilitar Tienda" as ToggleShop <<processing>>
  usecase "Eliminar Tienda" as DeleteShop <<processing>>
  usecase "Listar Encargados de Tienda" as ListShopManagers <<browsing>>
  usecase "Asignar Encargado de Tienda" as AssignShopManager <<processing>>
  usecase "Editar Encargado de Tienda" as EditShopManager <<processing>>
  usecase "Listar Espacios de Tienda" as ViewShopSpaces <<browsing>>
  usecase "Agregar Espacio" as AddShopSpace <<processing>>
  usecase "Editar Espacio" as EditShopSpace <<processing>>
  usecase "Eliminar Espacio" as DeleteShopSpace <<processing>>
  usecase "Reasignar Productos entre Espacios" as ReassignProducts <<processing>>
  usecase "Agregar Productos" as AddProduct <<processing>>
  usecase "Cerrar Sesión" as Logout <<processing>>
}


Admin --> CreateShop
Admin --> AddProduct
Admin --> Logout
Admin --> ViewShopDetail
Admin --> ViewShopSpaces
Admin --> AddShopSpaces

CreateShop <.. ViewShopDetail : <<include>>
ViewShopDetail <.. ViewShopSpaces : <<include>>
ViewShopDetail <.. AddShopSpaces : <<extends>>

@enduml