@startuml
allow_mixing

skinparam shadow false
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

actor "Usuario Invitado" as AnonUser

' 1. Selección de ubicación
usecase "Selección de Ubicación" as SelectLocation <<processing>>

' a. Ir a login -> i. Registrarse
usecase "Ir a Login" as GoToLogin <<browsing>>
usecase "Registrarse" as Register <<processing>>

' b, d, e. Flujos que llevan a Lista de Productos
usecase "Listar Productos Más Vendidos" as ViewMostSold <<browsing>>
usecase "Buscar Producto" as SearchProduct <<browsing>>
usecase "Listar Productos de Interés" as InterestProduct <<browsing>>
usecase "Ver Lista Tienda" as ViewStoreList <<browsing>>

' Sub-casos reutilizables
usecase "Ver Lista Producto" as ViewProductList <<browsing>>
usecase "Ver Detalle Producto" as ViewProductDetail <<browsing>>
usecase "Guardar Producto Interes" as SaveInterestProduct <<processing>>


usecase "Ver Detalle Tienda" as ViewStoreDetail <<browsing>>
usecase "Ver Resumen de Espacios Disponibles" as ViewSpaceList <<browsing>>
usecase "Recuperar contraseña" as Recover<<processing>>

' Relaciones

' 1. Ubicación
AnonUser --> SelectLocation

' a. Login
AnonUser --> GoToLogin
Register .> GoToLogin : <<extends>>
AnonUser --> Register
' Nota: Registrarse extiende la funcionalidad de Login (opción adicional)

AnonUser --> Recover

' d. Producto de interés -> Lista -> Guardar
AnonUser --> InterestProduct
InterestProduct ..> ViewProductDetail : <<include>>

' b. Producto más vendido -> Lista -> Detalle -> Guardar
AnonUser --> ViewMostSold
ViewMostSold ..> ViewProductDetail : <<include>>
ViewProductList ..> ViewProductDetail : <<include>>
SaveInterestProduct .> ViewProductDetail : <<extends>>




' c. Buscar producto -> Lista -> Guardar
AnonUser --> SearchProduct
SearchProduct ..> ViewProductList : <<include>>




' e. Ver lista tienda -> Detalle tienda -> Resumen de Espacios / Lista Productos
AnonUser --> ViewStoreList
ViewStoreList ..> ViewStoreDetail : <<include>>

' Detalle tienda tiene dos ramas:
ViewStoreDetail ..> ViewSpaceList : <<include>>
ViewStoreDetail ..> ViewProductList : <<include>>



@enduml