@startuml
allow_mixing

skinparam shadow false

skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

actor "Usuario Invitado" as AnonUser

  usecase "Establecer Ubicación" as SetLocation <<processing>>
  usecase "Ver Catálogo Tiendas" as ViewCatalog <<browsing>>
  usecase "Ver Detalle Tienda" as ViewShop <<browsing>>
  usecase "Ver Productos Tienda" as ViewShopProducts <<browsing>>
  usecase "Buscar Productos (Global)" as SearchGlobal <<browsing>>
  usecase "Ver Detalle de Producto" as ViewProductDetail <<browsing>>
  usecase "Guardar Productos de Interés" as SaveFavoriteProducts <<processing>>
  usecase "Ver Productos de Interes" as ViewFavoriteProducts <<browsing>>
  usecase "Ver Producto más vendido" as ViewMostSoldProducts <<browsing>>

  usecase "Ir a Login" as GoLogin <<processing>>
  usecase "Registrarse" as register <<processing>>

AnonUser --> SetLocation
AnonUser --> ViewCatalog
AnonUser --> SearchGlobal
AnonUser --> GoLogin
AnonUser --> register
AnonUser --> ViewProductDetail
AnonUser --> SaveFavoriteProducts
AnonUser --> ViewFavoriteProducts
AnonUser --> ViewMostSoldProducts

'TODO: Discuss with others
SetLocation <.. ViewCatalog : <<iSnclude>>
SetLocation <.. SearchGlobal : <<include>>

ViewProductDetail <.. SaveFavoriteProducts : <<extends>>
GoLogin <.. register : <<extends>>
ViewShopProducts <.. ViewProductDetail : <<extends>>
SearchGlobal <.. ViewProductDetail : <<extends>>
ViewCatalog ..> ViewShop : <<include>>
ViewShop ..> ViewShopProducts : <<include>>
@enduml