@startuml entrepreneur_login_content_model
skinparam classAttributeIconSize 0
skinparam shadow false
skinparam roundCorner 15

skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Content Model - Acceso" {

  class Usuario {
    + userId : UUID
    + name : String
    + email : String
    + phone : String
    + activeFlag : Boolean
    + createdDate : DateTime
    + lastLogin: DateTime
  }

  class Credencial {
    + credentialId : UUID
    + userId : UUID
    + passwordHas : String
    + passwordSalt : String
    + status : String  'ACTIVE | LOCKED | RESET_REQUIRED
    + failedAttempts : int
    + lastPasswordChange : DateTime
  }

  class Sesion {
    + sessionId : UUID
    + userId : UUID
    + token : String
    + createdAt : DateTime
    + expiresAt : DateTime
    + revoked : Boolean
  }

  class SolicitudRegistro {
    + request_id : UUID
    + name : String
    + email : String
    + phone : String
    + password_hash : String
    + city : UUID
    + colectivoId : UUID
    + cantidadEspacio : int
    + estado : String  'PENDIENTE | APROBADA | RECHAZADA
    + created_at : DateTime
  }

  class Ciudad {
    + cityId : UUID
    + nombre : String
  }

  class Colectivo {
    + colectivoId : UUID
    + nombre : String
    + cityId : UUID
    + activeFlag : Boolean
  }

  class RecuperacionAcceso {
    + recoveryId : UUID
    + identificador : String  'email o celular
    + canal : String          'EMAIL | SMS
    + codigo : String
    + expIn : DateTime
    + used : Boolean
    + created_at : DateTime
  }

  Usuario "1" -- "1" Credencial : posee >
  Usuario "1" -- "0..*" Sesion : inicia >

  SolicitudRegistro "0..*" --> "1" Ciudad : selecciona >
  SolicitudRegistro "0..*" --> "1" Colectivo : solicita >
  Ciudad "1" -- "0..*" Colectivo : contiene >

  RecuperacionAcceso "0..*" --> "0..1" Usuario : (si existe) >
}
@enduml



