@startuml landingPage_requirements
allow_mixing

skinparam shadow false

skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

actor "Usuario Anónimo" as AnonUser
package "Requirements Landing Page" {

  usecase "Establecer Ubicación" as SetLocation <<processing>>
  usecase "Ver Catálogo Tiendas" as ViewCatalog <<browsing>>
  usecase "Ver Detalle Tienda" as ViewShop <<browsing>>
  usecase "Ver Productos Tienda" as ViewShopProducts <<browsing>>
  usecase "Buscar Productos (Global)" as SearchGlobal <<browsing>>
  usecase "Ver Detalle de Producto" as ViewProductDetail <<browsing>>
  usecase "Guardar Productos de Interés" as SaveFavoriteProducts <<processing>>
  usecase "Ver Productos de Interes" as ViewFavoriteProducts <<browsing>>
  usecase "Create Categoria General de Producto" as CreateGeneralCategory <<processing>>
  usecase "Listar Categorias Generales de Producto" as ListGeneralCategories <<browsing>>
  usecase "Crear Clasificacion de Emprendimientos" as CreateEntrepreneurClassification <<processing>>
  usecase "Listar Clasificaciones de Emprendimientos" as ListEntrepreneurClass

  usecase "Ir a Login" as GoLogin <<processing>>
  usecase "Registrarse" as register <<processing>>
}

package "Actividades del Sistema" {
    usecase "Guardar Producto de Interes" as Sys_SaveFavoriteProducts <<systemAction>>
    usecase "Remover Producto de Interes" as Sys_RemoveFavoriteProducts <<systemAction>>
    usecase "Filtrar Productos por Ubicación" as Sys_FilterProductsByLocation <<systemAction>>
    usecase "Guardar Ubicación del Usuario" as Sys_SaveUserLocation <<systemAction>>
}

AnonUser --> SetLocation
AnonUser --> ViewCatalog
AnonUser --> SearchGlobal
AnonUser --> GoLogin
AnonUser --> register
AnonUser --> ViewProductDetail
AnonUser --> SaveFavoriteProducts
AnonUser --> ViewFavoriteProducts

'TODO: Discuss with others
SetLocation <.. ViewCatalog : <<include>>
SetLocation <.. SearchGlobal : <<include>>

ViewProductDetail <.. SaveFavoriteProducts : <<extends>>
GoLogin <.. register : <<extends>>
ViewShopProducts <.. ViewProductDetail : <<extends>>
SearchGlobal <.. ViewProductDetail : <<extends>>
ViewCatalog ..> ViewShop : <<include>>
ViewShop ..> ViewShopProducts : <<include>>

package "Activity Ver Catálogo Tiendas" {
  circle " " as BS_Start <<start>>
  circle " " as BS_End <<end>>
  skinparam circleBackgroundColor black

  class "Lista de Tiendas" as BS_List <<displayAction>> {
    {type=list}
    --
    <<displayPin>>
    + nombreTienda
    + fotoPortada
  }
  
  class "Seleccionar Tienda" as BS_Select <<userAction>> {
    --
    + selectedShopId
  }
  
  class "Página de Tienda" as BS_Page <<displayAction>> {
    --
    <<displayPin>>
    + nombre
    + fotoPortada {type=image}
    + telefono
    + direccion
    + numeroNegocios
    + listaNegocios {nombre, foto, numProductos}
    + catalogoProductos {type=list}
  }
  
  class "Seleccionar Producto" as BS_SelectProd <<userAction>> {
    --
    + selectedProductId
  }
  
  class "Detalle de Producto" as BS_ProdDetail <<displayAction>> {
    --
    <<displayPin>>
    + nombreProducto
    + precio
    + foto {type=image}
    + cantidad
  }

  BS_Start --> BS_List
  BS_List --> BS_Select : click shop
  BS_Select --> BS_Page : display
  BS_Page --> BS_SelectProd : click product
  BS_SelectProd --> BS_ProdDetail : view
  BS_ProdDetail --> BS_End
}

package "Activity Buscar Productos" {
  circle " " as SP_Start <<start>>
  circle " " as SP_End <<end>>

  class "Barra de Búsqueda" as SP_Form <<displayAction>> {
    {type=form}
    --
    <<interactionPin>>
    + nombreProductoinput
  }
  
  class "Ingresar nombre del producto" as SP_Input <<userAction>> {
    --
    + nombreProductoinput
  }
  
  class "Filtrar productos" as SP_Filter <<systemAction>> {
    {filtered}
  }
  
  class "Lista de Resultados" as SP_Results <<displayAction>> {
    {type=list}
    --
    <<displayPin>>
    + nombreProducto
    + precio
    + foto {type=image}
    + nombreNegocio
    + nombreTienda
  }
  
  SP_Start --> SP_Form
  SP_Form --> SP_Input : type
  SP_Input --> SP_Filter : search
  SP_Filter --> SP_Results : display
  SP_Results --> SP_End
}
@enduml
