@startuml login_requirements
allow_mixing

skinparam shadow false

skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Requirements Login" {
  usecase "Iniciar Sesión" as Login <<processing>>
  usecase "Recuperar Contraseña" as Recover <<processing>>
  usecase "Ver Dashboard" as ViewDash <<browsing>>
  
  actor "Usuario Administrador" as User
}

User --> Login
User --> Recover
Login ..> ViewDash 
Login <.. Recover 

package "Activity Login" {
  circle " " as AL_Start <<start>>
  circle " " as AL_End <<end>>
  skinparam circleBackgroundColor black

  class "Formulario Login" as AL_Form <<displayAction>> {
    {type=form}
    --
    <<interactionPin>>
    + email
    + password
  }
  
  class "Ingresar credenciales" as AL_Input <<userAction>> {

    + email
    + password
  }
  
  class "Validar Sesión" as AL_Process <<systemAction>> {
    {confirmed}
  }
  
  AL_Start --> AL_Form
  AL_Form --> AL_Input : submit
  AL_Input --> AL_Process : validate
  AL_Process --> AL_End : success
}

package "Activity Reset Password" {
  circle " " as AR_Start <<start>>
  circle " " as AR_End <<end>>

  class "Formulario Recuperar Contraseña" as AR_Form <<displayAction>> {
    {type=form}
    --
    <<interactionPin>>
    + email
  }
  
  class "Ingresar email" as AR_Input <<userAction>> {
    --
    + email
  }
  
  class "Validar Email" as AR_ValEmail <<systemAction>> {
    + token
  }
  
  class "Ingresar Token" as AR_Token <<userAction>> {
    --
    + receivedToken
  }
  
  class "Cambiar Contraseña" as AR_Change <<systemAction>> {
    --
    + newPassword
  }
  
  AR_Start --> AR_Form
  AR_Form --> AR_Input
  AR_Input --> AR_ValEmail : check
  AR_ValEmail --> AR_Token : success
  AR_Token --> AR_Change : update
  AR_Change --> AR_End
}
@enduml
