@startuml flujo_inicio_de_sesion

title Flujo de Proceso - Inicio de Sesion

start
:Boton Iniciar Sesion pulsado;
:<<userAction>> Ingresar credenciales;
:<<systemAction>> Validar credenciales;

if (Credenciales correctas?) then (si)
  :<<systemAction>> Completar acceso;
  :<<systemAction>> Verificar primer ingreso;

  if (Es primer ingreso?) then (si)
    :<<userAction>> Completar informacion faltante;
    :<<systemAction>> Guardar informacion;
    :<<systemAction>> Mostrar panel principal;
    stop
  else (no)
    :<<systemAction>> Mostrar panel principal;
    stop
  endif

else (no)
  :<<systemAction>> Mostrar error de acceso;
  stop
endif

@enduml
